
encoding_model: cl100k_base
skip_workflows: []
llm:
  type: openai_chat  # Keep this as 'openai_chat' for compatibility with the library
  model: qwen2:7b     # Use the local Llama model
  api_key: ollama
  model_supports_json: true
  request_timeout: 3600
  api_base: http://127.0.0.1:11434/v1  # Local Ollama API endpoint
  max_retries: 5
  max_retry_wait: 60.0
  sleep_on_rate_limit_recommendation: true
  concurrent_requests: 5

parallelization:
  stagger: 0.3
  num_threads: 10

async_mode: threaded

embeddings:
  async_mode: threaded
  llm:
    type: openai  # Keep this as 'openai' for compatibility
    model: qwen2:7b # Local embedding model
    api_base: http://127.0.0.1:11434  # Local Ollama API endpoint
    max_retries: 5
    max_retry_wait: 60.0
    sleep_on_rate_limit_recommendation: true
    concurrent_requests: 5
    batch_size: 8
    batch_max_tokens: 8000

chunks:
  size: 300
  overlap: 100
  group_by_columns: [id]
    
input:
  type: file
  file_type: text
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  type: file
  base_dir: "cache"

storage:
  type: file
  base_dir: "output/${timestamp}/artifacts"

reporting:
  type: file
  base_dir: "output/${timestamp}/reports"

entity_extraction:
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 0

summarize_descriptions:
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 0

community_report:
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false

umap:
  enabled: false

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:
  # Configurations remain unchanged

global_search:
  # Configurations remain unchanged
